config/routes.rb
Rails.application.routes.draw do
  resources :food_items do
    resources :orders
    resources :charges
  end
  get 'menu' => 'menu#index'
  get 'thank_you' => 'orders#thank_you'
  get 'contact_us' => 'welcome#contact_us'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  has_many :orders, dependent: :destroy
  validates :name, :price, :section, presence: true

  def default_image_url
    image_url.present? ? image_url : "http://loremflickr.com/320/240/#{CGI.escape name}"
  end

  def self.by_section(section)
    where(section: section)
  end

  def increase_view
    self.view_counter += 1
    self.save
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :name, :phone, :address, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => 'ab', :password => 'ab', :only => ['index']

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item.increase_view
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image_url)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    if params[:section].nil?
      @food_items = FoodItem.all.order(params[:sort_param])
    else
      @food_items = FoodItem.by_section(params[:section]).order(params[:sort_param])
    end
    @sections = %w(Novels SchoolBooks CompetitionBooks CollegeBooks)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @food_item = FoodItem.find params[:food_item_id]
  end

  def create
    @food_item = FoodItem.find params[:food_item_id]

    @order           = Order.new(order_params)
    @order.food_item = @food_item

    if @order.save
      redirect_to thank_you_path(:food_id => @food_item.id, :order_id => @order.id)
      flash[:success] = 'We received your order. Thank you!'
    else

      flash[:error] = "Error: #{@order.errors.full_messages.to_sentence}"
      render 'new'
    end
  end
def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
    flash[:notice] = "It is removed from your order"
    redirect_to order_path
  end
  private
  def order_params
    params.require(:order).permit(:name, :phone, :address, :coupon)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
  def section_btn_class(section)
    params[:section] == section ? '' : '-outline'
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
  def calculate_total
    sub_total        = food_info.price + 2
    discount_percent = customer_info.coupon == 'PRATEEK' ? 50 : 0
    {
        :sub_total        => sub_total,
        :discount_percent => discount_percent,
        :total            => sub_total - (sub_total.to_i / 100 * discount_percent)
    }
  end

  def customer_info
    Order.find(params[:order_id])
  end

  def food_info
    FoodItem.find(params[:food_id])
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
    <% if food_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

          <ul>
            <% food_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: "form-control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "form-control-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price, class: "form-control-label" %>
      <%= f.text_area :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :section, class: "form-control-label" %>
      <%= f.text_field :section, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image_url, class: "form-control-label" %>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>

    <%= f.submit 'Submit', class: 'actions btn btn-success-outline' %>

<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-striped table-condense">
  <thead class="thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><div style="width: 200px; word-wrap:break-word;"><%= food_item.image_url %></div></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-secondary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<div class="card-footer">
  <%= render 'form', food_item: @food_item %>
  <%= link_to 'Back', food_items_path, class: 'btn btn-secondary' %>
</div>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<p>
  <strong>Image preview:</strong><br>
  <%= image_tag @food_item.default_image_url %>
</p>

<%= link_to 'Back', :back, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby Bookshop</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <div class="container">
<nav class="navbar navbar-light bg-faded">    
     
      

        <a class="navbar-brand" href="/">Pyramid</a>
        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item <%= 'active' if current_page?(menu_url) %>">
            <%= link_to 'MENU', menu_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(contact_us_url) %>">
            <%= link_to 'CONTACT US', contact_us_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(food_items_url) %>">
            <%= link_to 'admin', food_items_url, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</head>

<body>
<div class="container">
  <% if flash[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <% if flash[:success] %>
      <div class="alert alert-info"><%= flash[:success] %></div>
  <% end %>
  <%= yield %>

  <footer class="footer">
    <p align="right">Prateek Arora</p>
  </footer>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/index.html.erb
<div align="center">
  <h1>Menu</h1>
</div>

<div class="container" align="center">
  <div class="btn-group" role="group">
    <%= link_to 'All', menu_path, class: 'btn btn-secondary-outline' %>
    <% @sections.each do |section| %>
        <%= link_to section, menu_path(section: section), class: "btn btn-primary#{section_btn_class(section)}" %>
    <% end %>
  </div>
</div>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownSortBy" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort by
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <%= link_to "Name", menu_path(:sort_param => "name", :section => params[:section]), class: "dropdown-item" %>
    <%= link_to "Price (low to high)", menu_path(:sort_param => "price ASC", :section => params[:section]), class: "dropdown-item" %>
    <%= link_to "Price (high to low)", menu_path(:sort_param => "price DESC", :section => params[:section]), class: "dropdown-item" %>
    <%= link_to "Most viewed", menu_path(:sort_param => "view_counter DESC", :section => params[:section]), class: "dropdown-item" %>
  </div>
</div>


<br>
<br>
<% @food_items.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.compact.each do |food_item| %>
          <div class="col-sm-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title"> <%= food_item.name.mb_chars.upcase %> </h4>
                <%= link_to '(show details)', food_item, class: "card-title" %>
              </div>
              <%= image_tag food_item.default_image_url, alt: 'the image url does not exist' %>
              <div class="card-block">
                <p class="card-text"> <%= number_to_currency(food_item.price, locale: :vn) %></p>
                <%= link_to 'Order now!', new_food_item_order_path(food_item.id), class: "btn btn-primary btn-sm" %>
                <br>
              </div>
              <div class="card-footer text-muted">
                <%= "Popularity: #{food_item.view_counter}" %><br>
                <%= food_item.orders.size %> order(s) have been made so far.
              </div>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/orders/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/orders/new.html.erb
<h1>
  <small>Order for</small> <%= @food_item.name %>
</h1>

<div class="row">
  <div class="col-sm-4">
    <%= form_for [@food_item, Order.new] do |f| %>
        <fieldset class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </fieldset>

        <fieldset class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </fieldset>

        <fieldset class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </fieldset>

        <fieldset class="form-group">
          <%= f.label :coupon %>
          <%= f.text_field :coupon, class: 'form-control' %>
        </fieldset>

        <%= f.submit 'Submit your order', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/orders/thank_you.html.erb
<div>
<h1 align="center">Thank you !</h1>

Thanks for using our service, <%= customer_info.name %><br>
Your order on <%= customer_info.created_at.strftime("%A, %B %d, %H:%M") %><br>
<br>
<table class="table table-striped">
  <tr>
    <td><strong><%= food_info.name %></strong></td>
    <td><%= number_to_currency(food_info.price, locale: :vn) %></td>
  </tr>
  <tr>
    <td>Delivery price</td>
    <td>20.000 </td>
  </tr>
  <tr>
    <td>Sub Total:</td>
    <td><%= number_to_currency(calculate_total[:sub_total], locale: :vn) %> </td>
  <tr>
    <td>Discount:</td>
    <td><%= calculate_total[:discount_percent ]%>%</td>
  </tr>
  <tr>
    <td>Total:</td>
    <td><strong><%= number_to_currency(calculate_total[:total], locale: :vn) %></strong></td>
  </tr>

</table>
<br>
We will call <%= customer_info.phone %> within 1 minute to verify the order. <br>
Your order will be delivered within 3 DAYS to <%= customer_info.address %>
</div>

app/views/welcome/contact_us.html.erb
<div align="center">
  <h1>Contact us</h1>
</div>

<div class="row">
  <div class="col-sm-4">
    <h2>Address</h2>
    <address>

      Pyramid Books & Stationary Shop
        39- Nathu Singh Market <br>
    </address>
  </div>
  <div class="col-sm-8">
    <h2>Live map</h2>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3505.505711893985!2d77.15268281483664!3d28.5245155824605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d1e78b3dfff35%3A0x49625bba95f2453!2sPyramid+Books+%26+Stationary+Shop!5e0!3m2!1sen!2sin!4v1493304947582" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">

  <table>
    <tr>
      <th>
        <h1 class="display-3">
          <small>Welcome to</small>
          <br>
          Pyramid Book Shop
        </h1>
      </th>
      <th>
        <%= image_tag "https://lscdn.azureedge.net/biz-live/img/347932-1091790-28022017124815.jpeg" %>
      </th>
    </tr>
  </table>
  <hr class="m-y-2">
  <p>Pick your book and order now!</p>

  <p class="lead">
    <%= link_to 'Menu', menu_path, class: 'btn btn-secondary' %>
    <%= link_to 'Contact us', contact_us_path, class: 'btn btn-secondary' %>
  </p>
</div>